services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # jangan pakai container_name
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_DATABASE: uas_fp
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    # jangan pakai container_name
    restart: always
    environment:
      MYSQL_DATABASE: uas_fp
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # jangan pakai container_name
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: "3306"
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    depends_on:
      - db

volumes:
  db_data:
