version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "${DB_PORT:-13307}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-18082}:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      - db
    # uncomment jika butuh akses via browser
    # ports:
    #   - "${APP_PORT:-18005}:8000"
