services:
  app:
    build: .
    depends_on: [db]
    environment:
      DB_HOST: db
      DB_PORT: 3306

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    # HAPUS blok "ports:" agar TIDAK expose 3307

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on: [db]
    environment:
      PMA_HOST: db
    ports:
      - "8082:80"   # ini boleh, untuk akses UI
volumes:
  db_data:
