pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'auliaanrhm'
        IMAGE_NAME = 'apps-go-cloud'
    }

    stages {
        stage('Checkout') {
            steps {
                echo '📥 Checkout SCM'
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo '🐳 Build Docker image'
                bat 'docker build -t %DOCKERHUB_USER%/%IMAGE_NAME%:latest .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                echo '📤 Push ke Docker Hub'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    bat 'docker login -u %DOCKER_USER% -p %DOCKER_PASS%'
                    bat 'docker push %DOCKERHUB_USER%/%IMAGE_NAME%:latest'
                }
            }
        }

        stage('Run Docker Compose') {
            steps {
                echo '🚀 docker compose up'
                bat 'docker compose down --remove-orphans'
                bat 'docker compose up -d --build'
            }
        }
    }

    post {
        always {
            echo '✅ Pipeline selesai'
        }
    }
}

